name: Changelog

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip changelog') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v6

      - name: Fetch base branch
        run: git fetch --no-tags origin main

      - name: Check news fragment
        run: uvx towncrier check --compare-with origin/main --config packages/collective-bpmnblock/towncrier.toml --dir packages/collective-bpmnblock
